# Generated by Django 3.0.3 on 2020-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200515_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='choice',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='number_of_sessional',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='year',
            field=models.IntegerField(default=True),
        ),
    ]
